# Generated by Django 4.2.10 on 2024-03-02 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_alter_comment_is_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='reply_to_reply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reps', to='posts.comment'),
        ),
    ]
